# Generated by Django 6.0.6 on 2026-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0)),
                ('total_distance_miles', models.FloatField(default=0)),
                ('total_drive_hours', models.FloatField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('days', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
